using System;
using System.Globalization;
using System.IO;
using System.Numerics;

namespace NANOVNACSharp
{
    /// <summary>
    /// Writes S-parameter data in Touchstone S1P format.
    ///
    /// Produces files with a standard header line ("# MHz S RI R {z0}") followed
    /// by rows of frequency (MHz), real, and imaginary values.
    /// </summary>
    public static class TouchstoneWriter
    {
        /// <summary>
        /// Write S-parameter data to a Touchstone S1P file.
        /// </summary>
        /// <param name="filePath">Output file path.</param>
        /// <param name="frequencies">Frequency array in Hz.</param>
        /// <param name="sData">Complex S-parameter data.</param>
        /// <param name="z0">Reference impedance in ohms (default 50).</param>
        public static void WriteS1P(string filePath, double[] frequencies, Complex[] sData, double z0 = 50.0)
        {
            using (StreamWriter writer = new StreamWriter(filePath))
            {
                writer.WriteLine("! Touchstone file generated by NANOVNACSharp");
                writer.WriteLine("! Date: {0}", DateTime.UtcNow.ToString("o"));
                writer.WriteLine(string.Format(CultureInfo.InvariantCulture,
                    "# MHz S RI R {0:F1}", z0));

                for (int i = 0; i < frequencies.Length && i < sData.Length; i++)
                {
                    double freqMHz = frequencies[i] / 1e6;
                    writer.WriteLine(string.Format(CultureInfo.InvariantCulture,
                        "{0:F6} {1:E12} {2:E12}",
                        freqMHz, sData[i].Real, sData[i].Imaginary));
                }
            }
        }
    }
}
